### ISSUE TITLE
Add a config file for each model

### ISSUE THREAD

**Issue by fcbond** [merrickchoo/vaderSentiment#6]
It should give the language, set any flags and offer a short description.

e.g.
```yaml
model: en_vader
lang: en
flags: 
 - NO
 - BUT
 - LEAST
citation: |
  Hutto, C.J. & Gilbert, E.E. (2014). VADER: A Parsimonious Rule-based Model for Sentiment Analysis of Social 
  Media Text. Eighth International Conference on Weblogs and Social Media (ICWSM-14). 
  Ann Arbor, MI, June 2014.
citation_url: "https://www.aaai.org/ocs/index.php/ICWSM/ICWSM14/paper/viewFile/8109/8122"
description: |
  The hand built model from the original VADER.
```
